global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'dashboard'

alerting:
 alertmanagers:
 - static_configs:
    - targets:
        - "172.20.130.121:9093"

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:  
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node
    static_configs:
      - targets: ['172.20.130.121:9100','pushgateway:9091']

  - job_name: 'media-sync-131'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
     - targets: ['172.20.130.121:8081']
       labels:
          instance: media-sync
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://172.20.130.121:16379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis-exporter:9121